## Tacotron 2 inference code 
Edit the variables **checkpoint_path** and **text** to match yours and run the entire code to generate plots of mel outputs, alignments and audio synthesis from the generated mel-spectrogram using Griffin-Lim.

#### Import libraries and setup matplotlib

In [1]:
import matplotlib
%matplotlib inline
import matplotlib.pylab as plt

import IPython.display as ipd

import sys
sys.path.append('waveglow/')
import numpy as np
import torch

from hparams import create_hparams
from model import Tacotron2
from layers import TacotronSTFT, STFT
from audio_processing import griffin_lim
from train import load_model
from text import text_to_sequence
from denoiser import Denoiser

2024-02-07 19:42:23.148924: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-07 19:42:23.770573: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
def plot_data(data, figsize=(16, 4)):
    fig, axes = plt.subplots(1, len(data), figsize=figsize)
    for i in range(len(data)):
        axes[i].imshow(data[i], aspect='auto', origin='upper', 
                       interpolation='none')
    plt.savefig('myfilename.png', dpi=100)
    plt.show()

#### Setup hparams

In [3]:
hparams = create_hparams()
hparams.sampling_rate = 22050

#### Load model from checkpoint

In [4]:
checkpoint_path = "tacotron2_statedict.pt"
model = load_model(hparams)
model.load_state_dict(torch.load(checkpoint_path)['state_dict'])
_ = model.cuda().eval()

#### Load WaveGlow for mel2audio synthesis and denoiser

In [5]:
waveglow_path = 'waveglow_256channels_universal_v5.pt'
waveglow = torch.load(waveglow_path)['model']
waveglow.cuda().eval()
for k in waveglow.convinv:
    k.float()
denoiser = Denoiser(waveglow)

/opt/conda/lib/python3.10/site-packages/torch/serialization.py:888: SourceChangeWarning: source code of class 'torch.nn.modules.conv.ConvTranspose1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/opt/conda/lib/python3.10/site-packages/torch/serialization.py:888: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/opt/conda/lib/python3.10/site-packages/torch/serialization.py:888: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv1d' has changed. you can retrieve the original source code by accessing the object's source attribute

#### Prepare text input

In [6]:
text = "Waveglow is really awesome! and use the patch tool to revert the changes."
sequence = np.array(text_to_sequence(text, ['english_cleaners']))[None, :]
sequence = torch.autograd.Variable(
    torch.from_numpy(sequence)).cuda().long()

In [7]:
sequence

tensor([[60, 38, 59, 42, 44, 49, 52, 60, 11, 46, 56, 11, 55, 42, 38, 49, 49, 62,
         11, 38, 60, 42, 56, 52, 50, 42,  2, 11, 38, 51, 41, 11, 58, 56, 42, 11,
         57, 45, 42, 11, 53, 38, 57, 40, 45, 11, 57, 52, 52, 49, 11, 57, 52, 11,
         55, 42, 59, 42, 55, 57, 11, 57, 45, 42, 11, 40, 45, 38, 51, 44, 42, 56,
          7]], device='cuda:0')

#### Decode text input and plot results

In [8]:
mel_outputs, mel_outputs_postnet, _, alignments = model.inference(sequence)
plot_data((mel_outputs.float().data.cpu().numpy()[0],
           mel_outputs_postnet.float().data.cpu().numpy()[0],
           alignments.float().data.cpu().numpy()[0].T))

In [9]:
fig, ax = plt.subplots()  # Create a figure containing a single axes.
ax.plot([1, 2, 3, 4], [1, 4, 2, 3])  # Plot some data on the axes.

In [10]:

plt.show()
mel_outputs_postnet.float().data.cpu().numpy()[0]

array([[ -7.2897835,  -6.6766148,  -6.741451 , ...,  -8.975195 ,
         -8.944773 ,  -8.501391 ],
       [ -6.793525 ,  -6.107064 ,  -5.875621 , ...,  -7.5491295,
         -7.5353436,  -7.332028 ],
       [ -6.1054854,  -5.387515 ,  -5.0793915, ...,  -6.380245 ,
         -6.386731 ,  -6.461527 ],
       ...,
       [-10.2489395,  -9.982705 ,  -9.6190815, ...,  -9.077162 ,
         -9.147791 ,  -9.189238 ],
       [-10.264349 ,  -9.9261265,  -9.396697 , ...,  -9.133153 ,
         -9.166478 ,  -9.189357 ],
       [-10.3235655,  -9.949645 ,  -9.337581 , ...,  -9.17207  ,
         -9.177858 ,  -9.200355 ]], dtype=float32)

#### Synthesize audio from spectrogram using WaveGlow

In [11]:
with torch.no_grad():
    audio = waveglow.infer(mel_outputs_postnet, sigma=0.666)
ipd.Audio(audio[0].data.cpu().numpy(), rate=hparams.sampling_rate)

In [12]:
audio[0].data.cpu().numpy()

array([ 2.0969918e-04,  1.9054455e-04,  1.5549386e-04, ...,
        2.1946596e-05, -8.2166807e-05, -1.9936143e-04], dtype=float32)

#### (Optional) Remove WaveGlow bias

In [13]:
audio_denoised = denoiser(audio, strength=0.01)[:, 0]
ipd.Audio(audio_denoised.cpu().numpy(), rate=hparams.sampling_rate) 